/* 
 * Iconomi API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Statistics
    /// </summary>
    [DataContract]
        public partial class Statistics :  IEquatable<Statistics>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Statistics" /> class.
        /// </summary>
        /// <param name="ticker">ticker.</param>
        /// <param name="currency">currency.</param>
        /// <param name="returns">returns.</param>
        /// <param name="volatility">volatility.</param>
        /// <param name="maxDrawdown">maxDrawdown.</param>
        public Statistics(string ticker = default(string), string currency = default(string), StatisticsReturns returns = default(StatisticsReturns), StatisticsReturns volatility = default(StatisticsReturns), StatisticsReturns maxDrawdown = default(StatisticsReturns))
        {
            this.Ticker = ticker;
            this.Currency = currency;
            this.Returns = returns;
            this.Volatility = volatility;
            this.MaxDrawdown = maxDrawdown;
        }
        
        /// <summary>
        /// Gets or Sets Ticker
        /// </summary>
        [DataMember(Name="ticker", EmitDefaultValue=false)]
        public string Ticker { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name="currency", EmitDefaultValue=false)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets Returns
        /// </summary>
        [DataMember(Name="returns", EmitDefaultValue=false)]
        public StatisticsReturns Returns { get; set; }

        /// <summary>
        /// Gets or Sets Volatility
        /// </summary>
        [DataMember(Name="volatility", EmitDefaultValue=false)]
        public StatisticsReturns Volatility { get; set; }

        /// <summary>
        /// Gets or Sets MaxDrawdown
        /// </summary>
        [DataMember(Name="maxDrawdown", EmitDefaultValue=false)]
        public StatisticsReturns MaxDrawdown { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Statistics {\n");
            sb.Append("  Ticker: ").Append(Ticker).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Returns: ").Append(Returns).Append("\n");
            sb.Append("  Volatility: ").Append(Volatility).Append("\n");
            sb.Append("  MaxDrawdown: ").Append(MaxDrawdown).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Statistics);
        }

        /// <summary>
        /// Returns true if Statistics instances are equal
        /// </summary>
        /// <param name="input">Instance of Statistics to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Statistics input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Ticker == input.Ticker ||
                    (this.Ticker != null &&
                    this.Ticker.Equals(input.Ticker))
                ) && 
                (
                    this.Currency == input.Currency ||
                    (this.Currency != null &&
                    this.Currency.Equals(input.Currency))
                ) && 
                (
                    this.Returns == input.Returns ||
                    (this.Returns != null &&
                    this.Returns.Equals(input.Returns))
                ) && 
                (
                    this.Volatility == input.Volatility ||
                    (this.Volatility != null &&
                    this.Volatility.Equals(input.Volatility))
                ) && 
                (
                    this.MaxDrawdown == input.MaxDrawdown ||
                    (this.MaxDrawdown != null &&
                    this.MaxDrawdown.Equals(input.MaxDrawdown))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Ticker != null)
                    hashCode = hashCode * 59 + this.Ticker.GetHashCode();
                if (this.Currency != null)
                    hashCode = hashCode * 59 + this.Currency.GetHashCode();
                if (this.Returns != null)
                    hashCode = hashCode * 59 + this.Returns.GetHashCode();
                if (this.Volatility != null)
                    hashCode = hashCode * 59 + this.Volatility.GetHashCode();
                if (this.MaxDrawdown != null)
                    hashCode = hashCode * 59 + this.MaxDrawdown.GetHashCode();
                return hashCode;
            }
        }
    }
}
