/* 
 * Iconomi API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using IconomiApi.Client;
using IconomiApi.Model;

namespace IconomiApi.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IStrategiesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Historical information
        /// </summary>
        /// <remarks>
        /// The price history returns data points for the given period. Different granulation of data can be returned based on the length of the period provided from daily to 5 minute (one  price point per period).  From and to are optional parameters (both are either suplied or neither is supplied). If from/to are not supplied a default of last month is returned with hourly granulation.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to"> (optional)</param>
        /// <param name="granulation">Granulation for price points. See granulation enumeration section for more details. (optional)</param>
        /// <returns>Chart</returns>
        Chart Charts (string ticker, string currency = null, long? from = null, long? to = null, string granulation = null);

        /// <summary>
        /// Historical information
        /// </summary>
        /// <remarks>
        /// The price history returns data points for the given period. Different granulation of data can be returned based on the length of the period provided from daily to 5 minute (one  price point per period).  From and to are optional parameters (both are either suplied or neither is supplied). If from/to are not supplied a default of last month is returned with hourly granulation.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to"> (optional)</param>
        /// <param name="granulation">Granulation for price points. See granulation enumeration section for more details. (optional)</param>
        /// <returns>ApiResponse of Chart</returns>
        ApiResponse<Chart> ChartsWithHttpInfo (string ticker, string currency = null, long? from = null, long? to = null, string granulation = null);
        /// <summary>
        /// Balance
        /// </summary>
        /// <remarks>
        /// Endpoint requires manager authentication with institutional role. Returns live balances underlying assets of strategy.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <returns>StrategyBalance</returns>
        StrategyBalance DaaBalance (string ticker);

        /// <summary>
        /// Balance
        /// </summary>
        /// <remarks>
        /// Endpoint requires manager authentication with institutional role. Returns live balances underlying assets of strategy.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <returns>ApiResponse of StrategyBalance</returns>
        ApiResponse<StrategyBalance> DaaBalanceWithHttpInfo (string ticker);
        /// <summary>
        /// Current ticker
        /// </summary>
        /// <remarks>
        /// Returns the current ticker of the Strategy. The price is refreshed every minute.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Ticker</returns>
        Ticker DaaPrice (string ticker, string currency = null);

        /// <summary>
        /// Current ticker
        /// </summary>
        /// <remarks>
        /// Returns the current ticker of the Strategy. The price is refreshed every minute.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>ApiResponse of Ticker</returns>
        ApiResponse<Ticker> DaaPriceWithHttpInfo (string ticker, string currency = null);
        /// <summary>
        /// Statistics
        /// </summary>
        /// <remarks>
        /// Returns statistics of the strategy; returns, max drawdown and volatility for strategy.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Statistics</returns>
        Statistics GetStatistics (string ticker, string currency = null);

        /// <summary>
        /// Statistics
        /// </summary>
        /// <remarks>
        /// Returns statistics of the strategy; returns, max drawdown and volatility for strategy.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>ApiResponse of Statistics</returns>
        ApiResponse<Statistics> GetStatisticsWithHttpInfo (string ticker, string currency = null);
        /// <summary>
        /// Strategy details
        /// </summary>
        /// <remarks>
        /// Returns information about one specific strategy.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker">Ticker of structure</param>
        /// <returns>Strategy</returns>
        Strategy Info (string ticker);

        /// <summary>
        /// Strategy details
        /// </summary>
        /// <remarks>
        /// Returns information about one specific strategy.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker">Ticker of structure</param>
        /// <returns>ApiResponse of Strategy</returns>
        ApiResponse<Strategy> InfoWithHttpInfo (string ticker);
        /// <summary>
        /// List of Strategies
        /// </summary>
        /// <remarks>
        /// Returns a list of all public Strategies.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;Strategy&gt;</returns>
        List<Strategy> StrategyList ();

        /// <summary>
        /// List of Strategies
        /// </summary>
        /// <remarks>
        /// Returns a list of all public Strategies.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;Strategy&gt;</returns>
        ApiResponse<List<Strategy>> StrategyListWithHttpInfo ();
        /// <summary>
        /// Structure
        /// </summary>
        /// <remarks>
        /// Returns the current structure of a strategy. The same result entity is returned  for both PASSIVE and ACTIVE type DAAs, but for ACTIVE DAAs rebalancedWeight  and targetWeight are always set to 0.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Structure</returns>
        Structure Structure (string ticker, string currency = null);

        /// <summary>
        /// Structure
        /// </summary>
        /// <remarks>
        /// Returns the current structure of a strategy. The same result entity is returned  for both PASSIVE and ACTIVE type DAAs, but for ACTIVE DAAs rebalancedWeight  and targetWeight are always set to 0.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>ApiResponse of Structure</returns>
        ApiResponse<Structure> StructureWithHttpInfo (string ticker, string currency = null);
        /// <summary>
        /// Structure
        /// </summary>
        /// <remarks>
        /// Endpoint requires authentication. Creates and submits a new structure for a given strategy.   Response is the same object as GET to /v1/strategies/{ticker}/structure.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Structure</returns>
        Structure SubmitStructure (string ticker, StructureSubmit body = null);

        /// <summary>
        /// Structure
        /// </summary>
        /// <remarks>
        /// Endpoint requires authentication. Creates and submits a new structure for a given strategy.   Response is the same object as GET to /v1/strategies/{ticker}/structure.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Structure</returns>
        ApiResponse<Structure> SubmitStructureWithHttpInfo (string ticker, StructureSubmit body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Historical information
        /// </summary>
        /// <remarks>
        /// The price history returns data points for the given period. Different granulation of data can be returned based on the length of the period provided from daily to 5 minute (one  price point per period).  From and to are optional parameters (both are either suplied or neither is supplied). If from/to are not supplied a default of last month is returned with hourly granulation.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to"> (optional)</param>
        /// <param name="granulation">Granulation for price points. See granulation enumeration section for more details. (optional)</param>
        /// <returns>Task of Chart</returns>
        System.Threading.Tasks.Task<Chart> ChartsAsync (string ticker, string currency = null, long? from = null, long? to = null, string granulation = null);

        /// <summary>
        /// Historical information
        /// </summary>
        /// <remarks>
        /// The price history returns data points for the given period. Different granulation of data can be returned based on the length of the period provided from daily to 5 minute (one  price point per period).  From and to are optional parameters (both are either suplied or neither is supplied). If from/to are not supplied a default of last month is returned with hourly granulation.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to"> (optional)</param>
        /// <param name="granulation">Granulation for price points. See granulation enumeration section for more details. (optional)</param>
        /// <returns>Task of ApiResponse (Chart)</returns>
        System.Threading.Tasks.Task<ApiResponse<Chart>> ChartsAsyncWithHttpInfo (string ticker, string currency = null, long? from = null, long? to = null, string granulation = null);
        /// <summary>
        /// Balance
        /// </summary>
        /// <remarks>
        /// Endpoint requires manager authentication with institutional role. Returns live balances underlying assets of strategy.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <returns>Task of StrategyBalance</returns>
        System.Threading.Tasks.Task<StrategyBalance> DaaBalanceAsync (string ticker);

        /// <summary>
        /// Balance
        /// </summary>
        /// <remarks>
        /// Endpoint requires manager authentication with institutional role. Returns live balances underlying assets of strategy.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <returns>Task of ApiResponse (StrategyBalance)</returns>
        System.Threading.Tasks.Task<ApiResponse<StrategyBalance>> DaaBalanceAsyncWithHttpInfo (string ticker);
        /// <summary>
        /// Current ticker
        /// </summary>
        /// <remarks>
        /// Returns the current ticker of the Strategy. The price is refreshed every minute.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Task of Ticker</returns>
        System.Threading.Tasks.Task<Ticker> DaaPriceAsync (string ticker, string currency = null);

        /// <summary>
        /// Current ticker
        /// </summary>
        /// <remarks>
        /// Returns the current ticker of the Strategy. The price is refreshed every minute.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Task of ApiResponse (Ticker)</returns>
        System.Threading.Tasks.Task<ApiResponse<Ticker>> DaaPriceAsyncWithHttpInfo (string ticker, string currency = null);
        /// <summary>
        /// Statistics
        /// </summary>
        /// <remarks>
        /// Returns statistics of the strategy; returns, max drawdown and volatility for strategy.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Task of Statistics</returns>
        System.Threading.Tasks.Task<Statistics> GetStatisticsAsync (string ticker, string currency = null);

        /// <summary>
        /// Statistics
        /// </summary>
        /// <remarks>
        /// Returns statistics of the strategy; returns, max drawdown and volatility for strategy.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Task of ApiResponse (Statistics)</returns>
        System.Threading.Tasks.Task<ApiResponse<Statistics>> GetStatisticsAsyncWithHttpInfo (string ticker, string currency = null);
        /// <summary>
        /// Strategy details
        /// </summary>
        /// <remarks>
        /// Returns information about one specific strategy.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker">Ticker of structure</param>
        /// <returns>Task of Strategy</returns>
        System.Threading.Tasks.Task<Strategy> InfoAsync (string ticker);

        /// <summary>
        /// Strategy details
        /// </summary>
        /// <remarks>
        /// Returns information about one specific strategy.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker">Ticker of structure</param>
        /// <returns>Task of ApiResponse (Strategy)</returns>
        System.Threading.Tasks.Task<ApiResponse<Strategy>> InfoAsyncWithHttpInfo (string ticker);
        /// <summary>
        /// List of Strategies
        /// </summary>
        /// <remarks>
        /// Returns a list of all public Strategies.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;Strategy&gt;</returns>
        System.Threading.Tasks.Task<List<Strategy>> StrategyListAsync ();

        /// <summary>
        /// List of Strategies
        /// </summary>
        /// <remarks>
        /// Returns a list of all public Strategies.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;Strategy&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Strategy>>> StrategyListAsyncWithHttpInfo ();
        /// <summary>
        /// Structure
        /// </summary>
        /// <remarks>
        /// Returns the current structure of a strategy. The same result entity is returned  for both PASSIVE and ACTIVE type DAAs, but for ACTIVE DAAs rebalancedWeight  and targetWeight are always set to 0.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Task of Structure</returns>
        System.Threading.Tasks.Task<Structure> StructureAsync (string ticker, string currency = null);

        /// <summary>
        /// Structure
        /// </summary>
        /// <remarks>
        /// Returns the current structure of a strategy. The same result entity is returned  for both PASSIVE and ACTIVE type DAAs, but for ACTIVE DAAs rebalancedWeight  and targetWeight are always set to 0.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Task of ApiResponse (Structure)</returns>
        System.Threading.Tasks.Task<ApiResponse<Structure>> StructureAsyncWithHttpInfo (string ticker, string currency = null);
        /// <summary>
        /// Structure
        /// </summary>
        /// <remarks>
        /// Endpoint requires authentication. Creates and submits a new structure for a given strategy.   Response is the same object as GET to /v1/strategies/{ticker}/structure.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of Structure</returns>
        System.Threading.Tasks.Task<Structure> SubmitStructureAsync (string ticker, StructureSubmit body = null);

        /// <summary>
        /// Structure
        /// </summary>
        /// <remarks>
        /// Endpoint requires authentication. Creates and submits a new structure for a given strategy.   Response is the same object as GET to /v1/strategies/{ticker}/structure.
        /// </remarks>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (Structure)</returns>
        System.Threading.Tasks.Task<ApiResponse<Structure>> SubmitStructureAsyncWithHttpInfo (string ticker, StructureSubmit body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class StrategiesApi : IStrategiesApi
    {
        private IconomiApi.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StrategiesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StrategiesApi(String basePath)
        {
            this.Configuration = new IconomiApi.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IconomiApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StrategiesApi"/> class
        /// </summary>
        /// <returns></returns>
        public StrategiesApi()
        {
            this.Configuration = IconomiApi.Client.Configuration.Default;

            ExceptionFactory = IconomiApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StrategiesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StrategiesApi(IconomiApi.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IconomiApi.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IconomiApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IconomiApi.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IconomiApi.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Historical information The price history returns data points for the given period. Different granulation of data can be returned based on the length of the period provided from daily to 5 minute (one  price point per period).  From and to are optional parameters (both are either suplied or neither is supplied). If from/to are not supplied a default of last month is returned with hourly granulation.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to"> (optional)</param>
        /// <param name="granulation">Granulation for price points. See granulation enumeration section for more details. (optional)</param>
        /// <returns>Chart</returns>
        public Chart Charts (string ticker, string currency = null, long? from = null, long? to = null, string granulation = null)
        {
             ApiResponse<Chart> localVarResponse = ChartsWithHttpInfo(ticker, currency, from, to, granulation);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Historical information The price history returns data points for the given period. Different granulation of data can be returned based on the length of the period provided from daily to 5 minute (one  price point per period).  From and to are optional parameters (both are either suplied or neither is supplied). If from/to are not supplied a default of last month is returned with hourly granulation.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to"> (optional)</param>
        /// <param name="granulation">Granulation for price points. See granulation enumeration section for more details. (optional)</param>
        /// <returns>ApiResponse of Chart</returns>
        public ApiResponse< Chart > ChartsWithHttpInfo (string ticker, string currency = null, long? from = null, long? to = null, string granulation = null)
        {
            // verify the required parameter 'ticker' is set
            if (ticker == null)
                throw new ApiException(400, "Missing required parameter 'ticker' when calling StrategiesApi->Charts");

            var localVarPath = "./v1/strategies/{ticker}/pricehistory";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticker != null) localVarPathParams.Add("ticker", this.Configuration.ApiClient.ParameterToString(ticker)); // path parameter
            if (currency != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "currency", currency)); // query parameter
            if (from != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "from", from)); // query parameter
            if (to != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "to", to)); // query parameter
            if (granulation != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "granulation", granulation)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Charts", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Chart>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (Chart) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Chart)));
        }

        /// <summary>
        /// Historical information The price history returns data points for the given period. Different granulation of data can be returned based on the length of the period provided from daily to 5 minute (one  price point per period).  From and to are optional parameters (both are either suplied or neither is supplied). If from/to are not supplied a default of last month is returned with hourly granulation.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to"> (optional)</param>
        /// <param name="granulation">Granulation for price points. See granulation enumeration section for more details. (optional)</param>
        /// <returns>Task of Chart</returns>
        public async System.Threading.Tasks.Task<Chart> ChartsAsync (string ticker, string currency = null, long? from = null, long? to = null, string granulation = null)
        {
             ApiResponse<Chart> localVarResponse = await ChartsAsyncWithHttpInfo(ticker, currency, from, to, granulation);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Historical information The price history returns data points for the given period. Different granulation of data can be returned based on the length of the period provided from daily to 5 minute (one  price point per period).  From and to are optional parameters (both are either suplied or neither is supplied). If from/to are not supplied a default of last month is returned with hourly granulation.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <param name="from"> (optional)</param>
        /// <param name="to"> (optional)</param>
        /// <param name="granulation">Granulation for price points. See granulation enumeration section for more details. (optional)</param>
        /// <returns>Task of ApiResponse (Chart)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Chart>> ChartsAsyncWithHttpInfo (string ticker, string currency = null, long? from = null, long? to = null, string granulation = null)
        {
            // verify the required parameter 'ticker' is set
            if (ticker == null)
                throw new ApiException(400, "Missing required parameter 'ticker' when calling StrategiesApi->Charts");

            var localVarPath = "./v1/strategies/{ticker}/pricehistory";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticker != null) localVarPathParams.Add("ticker", this.Configuration.ApiClient.ParameterToString(ticker)); // path parameter
            if (currency != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "currency", currency)); // query parameter
            if (from != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "from", from)); // query parameter
            if (to != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "to", to)); // query parameter
            if (granulation != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "granulation", granulation)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Charts", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Chart>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (Chart) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Chart)));
        }

        /// <summary>
        /// Balance Endpoint requires manager authentication with institutional role. Returns live balances underlying assets of strategy.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <returns>StrategyBalance</returns>
        public StrategyBalance DaaBalance (string ticker)
        {
             ApiResponse<StrategyBalance> localVarResponse = DaaBalanceWithHttpInfo(ticker);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Balance Endpoint requires manager authentication with institutional role. Returns live balances underlying assets of strategy.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <returns>ApiResponse of StrategyBalance</returns>
        public ApiResponse< StrategyBalance > DaaBalanceWithHttpInfo (string ticker)
        {
            // verify the required parameter 'ticker' is set
            if (ticker == null)
                throw new ApiException(400, "Missing required parameter 'ticker' when calling StrategiesApi->DaaBalance");

            var localVarPath = "./v1/strategies/{ticker}/balance";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticker != null) localVarPathParams.Add("ticker", this.Configuration.ApiClient.ParameterToString(ticker)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DaaBalance", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StrategyBalance>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (StrategyBalance) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StrategyBalance)));
        }

        /// <summary>
        /// Balance Endpoint requires manager authentication with institutional role. Returns live balances underlying assets of strategy.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <returns>Task of StrategyBalance</returns>
        public async System.Threading.Tasks.Task<StrategyBalance> DaaBalanceAsync (string ticker)
        {
             ApiResponse<StrategyBalance> localVarResponse = await DaaBalanceAsyncWithHttpInfo(ticker);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Balance Endpoint requires manager authentication with institutional role. Returns live balances underlying assets of strategy.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <returns>Task of ApiResponse (StrategyBalance)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<StrategyBalance>> DaaBalanceAsyncWithHttpInfo (string ticker)
        {
            // verify the required parameter 'ticker' is set
            if (ticker == null)
                throw new ApiException(400, "Missing required parameter 'ticker' when calling StrategiesApi->DaaBalance");

            var localVarPath = "./v1/strategies/{ticker}/balance";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticker != null) localVarPathParams.Add("ticker", this.Configuration.ApiClient.ParameterToString(ticker)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DaaBalance", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StrategyBalance>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (StrategyBalance) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(StrategyBalance)));
        }

        /// <summary>
        /// Current ticker Returns the current ticker of the Strategy. The price is refreshed every minute.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Ticker</returns>
        public Ticker DaaPrice (string ticker, string currency = null)
        {
             ApiResponse<Ticker> localVarResponse = DaaPriceWithHttpInfo(ticker, currency);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Current ticker Returns the current ticker of the Strategy. The price is refreshed every minute.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>ApiResponse of Ticker</returns>
        public ApiResponse< Ticker > DaaPriceWithHttpInfo (string ticker, string currency = null)
        {
            // verify the required parameter 'ticker' is set
            if (ticker == null)
                throw new ApiException(400, "Missing required parameter 'ticker' when calling StrategiesApi->DaaPrice");

            var localVarPath = "./v1/strategies/{ticker}/price";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticker != null) localVarPathParams.Add("ticker", this.Configuration.ApiClient.ParameterToString(ticker)); // path parameter
            if (currency != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "currency", currency)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DaaPrice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Ticker>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (Ticker) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Ticker)));
        }

        /// <summary>
        /// Current ticker Returns the current ticker of the Strategy. The price is refreshed every minute.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Task of Ticker</returns>
        public async System.Threading.Tasks.Task<Ticker> DaaPriceAsync (string ticker, string currency = null)
        {
             ApiResponse<Ticker> localVarResponse = await DaaPriceAsyncWithHttpInfo(ticker, currency);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Current ticker Returns the current ticker of the Strategy. The price is refreshed every minute.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Task of ApiResponse (Ticker)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Ticker>> DaaPriceAsyncWithHttpInfo (string ticker, string currency = null)
        {
            // verify the required parameter 'ticker' is set
            if (ticker == null)
                throw new ApiException(400, "Missing required parameter 'ticker' when calling StrategiesApi->DaaPrice");

            var localVarPath = "./v1/strategies/{ticker}/price";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticker != null) localVarPathParams.Add("ticker", this.Configuration.ApiClient.ParameterToString(ticker)); // path parameter
            if (currency != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "currency", currency)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DaaPrice", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Ticker>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (Ticker) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Ticker)));
        }

        /// <summary>
        /// Statistics Returns statistics of the strategy; returns, max drawdown and volatility for strategy.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Statistics</returns>
        public Statistics GetStatistics (string ticker, string currency = null)
        {
             ApiResponse<Statistics> localVarResponse = GetStatisticsWithHttpInfo(ticker, currency);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Statistics Returns statistics of the strategy; returns, max drawdown and volatility for strategy.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>ApiResponse of Statistics</returns>
        public ApiResponse< Statistics > GetStatisticsWithHttpInfo (string ticker, string currency = null)
        {
            // verify the required parameter 'ticker' is set
            if (ticker == null)
                throw new ApiException(400, "Missing required parameter 'ticker' when calling StrategiesApi->GetStatistics");

            var localVarPath = "./v1/strategies/{ticker}/statistics";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticker != null) localVarPathParams.Add("ticker", this.Configuration.ApiClient.ParameterToString(ticker)); // path parameter
            if (currency != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "currency", currency)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetStatistics", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Statistics>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (Statistics) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Statistics)));
        }

        /// <summary>
        /// Statistics Returns statistics of the strategy; returns, max drawdown and volatility for strategy.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Task of Statistics</returns>
        public async System.Threading.Tasks.Task<Statistics> GetStatisticsAsync (string ticker, string currency = null)
        {
             ApiResponse<Statistics> localVarResponse = await GetStatisticsAsyncWithHttpInfo(ticker, currency);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Statistics Returns statistics of the strategy; returns, max drawdown and volatility for strategy.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Task of ApiResponse (Statistics)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Statistics>> GetStatisticsAsyncWithHttpInfo (string ticker, string currency = null)
        {
            // verify the required parameter 'ticker' is set
            if (ticker == null)
                throw new ApiException(400, "Missing required parameter 'ticker' when calling StrategiesApi->GetStatistics");

            var localVarPath = "./v1/strategies/{ticker}/statistics";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticker != null) localVarPathParams.Add("ticker", this.Configuration.ApiClient.ParameterToString(ticker)); // path parameter
            if (currency != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "currency", currency)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetStatistics", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Statistics>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (Statistics) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Statistics)));
        }

        /// <summary>
        /// Strategy details Returns information about one specific strategy.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker">Ticker of structure</param>
        /// <returns>Strategy</returns>
        public Strategy Info (string ticker)
        {
             ApiResponse<Strategy> localVarResponse = InfoWithHttpInfo(ticker);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Strategy details Returns information about one specific strategy.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker">Ticker of structure</param>
        /// <returns>ApiResponse of Strategy</returns>
        public ApiResponse< Strategy > InfoWithHttpInfo (string ticker)
        {
            // verify the required parameter 'ticker' is set
            if (ticker == null)
                throw new ApiException(400, "Missing required parameter 'ticker' when calling StrategiesApi->Info");

            var localVarPath = "./v1/strategies/{ticker}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticker != null) localVarPathParams.Add("ticker", this.Configuration.ApiClient.ParameterToString(ticker)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Info", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Strategy>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (Strategy) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Strategy)));
        }

        /// <summary>
        /// Strategy details Returns information about one specific strategy.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker">Ticker of structure</param>
        /// <returns>Task of Strategy</returns>
        public async System.Threading.Tasks.Task<Strategy> InfoAsync (string ticker)
        {
             ApiResponse<Strategy> localVarResponse = await InfoAsyncWithHttpInfo(ticker);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Strategy details Returns information about one specific strategy.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker">Ticker of structure</param>
        /// <returns>Task of ApiResponse (Strategy)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Strategy>> InfoAsyncWithHttpInfo (string ticker)
        {
            // verify the required parameter 'ticker' is set
            if (ticker == null)
                throw new ApiException(400, "Missing required parameter 'ticker' when calling StrategiesApi->Info");

            var localVarPath = "./v1/strategies/{ticker}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticker != null) localVarPathParams.Add("ticker", this.Configuration.ApiClient.ParameterToString(ticker)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Info", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Strategy>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (Strategy) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Strategy)));
        }

        /// <summary>
        /// List of Strategies Returns a list of all public Strategies.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;Strategy&gt;</returns>
        public List<Strategy> StrategyList ()
        {
             ApiResponse<List<Strategy>> localVarResponse = StrategyListWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// List of Strategies Returns a list of all public Strategies.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;Strategy&gt;</returns>
        public ApiResponse< List<Strategy> > StrategyListWithHttpInfo ()
        {

            var localVarPath = "./v1/strategies";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StrategyList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Strategy>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (List<Strategy>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Strategy>)));
        }

        /// <summary>
        /// List of Strategies Returns a list of all public Strategies.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;Strategy&gt;</returns>
        public async System.Threading.Tasks.Task<List<Strategy>> StrategyListAsync ()
        {
             ApiResponse<List<Strategy>> localVarResponse = await StrategyListAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// List of Strategies Returns a list of all public Strategies.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;Strategy&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Strategy>>> StrategyListAsyncWithHttpInfo ()
        {

            var localVarPath = "./v1/strategies";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StrategyList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Strategy>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (List<Strategy>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Strategy>)));
        }

        /// <summary>
        /// Structure Returns the current structure of a strategy. The same result entity is returned  for both PASSIVE and ACTIVE type DAAs, but for ACTIVE DAAs rebalancedWeight  and targetWeight are always set to 0.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Structure</returns>
        public Structure Structure (string ticker, string currency = null)
        {
             ApiResponse<Structure> localVarResponse = StructureWithHttpInfo(ticker, currency);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Structure Returns the current structure of a strategy. The same result entity is returned  for both PASSIVE and ACTIVE type DAAs, but for ACTIVE DAAs rebalancedWeight  and targetWeight are always set to 0.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>ApiResponse of Structure</returns>
        public ApiResponse< Structure > StructureWithHttpInfo (string ticker, string currency = null)
        {
            // verify the required parameter 'ticker' is set
            if (ticker == null)
                throw new ApiException(400, "Missing required parameter 'ticker' when calling StrategiesApi->Structure");

            var localVarPath = "./v1/strategies/{ticker}/structure";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticker != null) localVarPathParams.Add("ticker", this.Configuration.ApiClient.ParameterToString(ticker)); // path parameter
            if (currency != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "currency", currency)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Structure", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Structure>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (Structure) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Structure)));
        }

        /// <summary>
        /// Structure Returns the current structure of a strategy. The same result entity is returned  for both PASSIVE and ACTIVE type DAAs, but for ACTIVE DAAs rebalancedWeight  and targetWeight are always set to 0.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Task of Structure</returns>
        public async System.Threading.Tasks.Task<Structure> StructureAsync (string ticker, string currency = null)
        {
             ApiResponse<Structure> localVarResponse = await StructureAsyncWithHttpInfo(ticker, currency);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Structure Returns the current structure of a strategy. The same result entity is returned  for both PASSIVE and ACTIVE type DAAs, but for ACTIVE DAAs rebalancedWeight  and targetWeight are always set to 0.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="currency"> (optional, default to USD)</param>
        /// <returns>Task of ApiResponse (Structure)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Structure>> StructureAsyncWithHttpInfo (string ticker, string currency = null)
        {
            // verify the required parameter 'ticker' is set
            if (ticker == null)
                throw new ApiException(400, "Missing required parameter 'ticker' when calling StrategiesApi->Structure");

            var localVarPath = "./v1/strategies/{ticker}/structure";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticker != null) localVarPathParams.Add("ticker", this.Configuration.ApiClient.ParameterToString(ticker)); // path parameter
            if (currency != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "currency", currency)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Structure", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Structure>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (Structure) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Structure)));
        }

        /// <summary>
        /// Structure Endpoint requires authentication. Creates and submits a new structure for a given strategy.   Response is the same object as GET to /v1/strategies/{ticker}/structure.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Structure</returns>
        public Structure SubmitStructure (string ticker, StructureSubmit body = null)
        {
             ApiResponse<Structure> localVarResponse = SubmitStructureWithHttpInfo(ticker, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Structure Endpoint requires authentication. Creates and submits a new structure for a given strategy.   Response is the same object as GET to /v1/strategies/{ticker}/structure.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Structure</returns>
        public ApiResponse< Structure > SubmitStructureWithHttpInfo (string ticker, StructureSubmit body = null)
        {
            // verify the required parameter 'ticker' is set
            if (ticker == null)
                throw new ApiException(400, "Missing required parameter 'ticker' when calling StrategiesApi->SubmitStructure");

            var localVarPath = "./v1/strategies/{ticker}/structure";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticker != null) localVarPathParams.Add("ticker", this.Configuration.ApiClient.ParameterToString(ticker)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ICN-API-KEY")))
            {
                localVarHeaderParams["ICN-API-KEY"] = this.Configuration.GetApiKeyWithPrefix("ICN-API-KEY");
            }
            // authentication (ApiSign) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ICN-SIGN")))
            {
                localVarHeaderParams["ICN-SIGN"] = this.Configuration.GetApiKeyWithPrefix("ICN-SIGN");
            }
            // authentication (ApiTimestamp) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ICN-TIMESTAMP")))
            {
                localVarHeaderParams["ICN-TIMESTAMP"] = this.Configuration.GetApiKeyWithPrefix("ICN-TIMESTAMP");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubmitStructure", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Structure>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (Structure) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Structure)));
        }

        /// <summary>
        /// Structure Endpoint requires authentication. Creates and submits a new structure for a given strategy.   Response is the same object as GET to /v1/strategies/{ticker}/structure.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of Structure</returns>
        public async System.Threading.Tasks.Task<Structure> SubmitStructureAsync (string ticker, StructureSubmit body = null)
        {
             ApiResponse<Structure> localVarResponse = await SubmitStructureAsyncWithHttpInfo(ticker, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Structure Endpoint requires authentication. Creates and submits a new structure for a given strategy.   Response is the same object as GET to /v1/strategies/{ticker}/structure.
        /// </summary>
        /// <exception cref="IconomiApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ticker"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (Structure)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Structure>> SubmitStructureAsyncWithHttpInfo (string ticker, StructureSubmit body = null)
        {
            // verify the required parameter 'ticker' is set
            if (ticker == null)
                throw new ApiException(400, "Missing required parameter 'ticker' when calling StrategiesApi->SubmitStructure");

            var localVarPath = "./v1/strategies/{ticker}/structure";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "*/*",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (ticker != null) localVarPathParams.Add("ticker", this.Configuration.ApiClient.ParameterToString(ticker)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (ApiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ICN-API-KEY")))
            {
                localVarHeaderParams["ICN-API-KEY"] = this.Configuration.GetApiKeyWithPrefix("ICN-API-KEY");
            }
            // authentication (ApiSign) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ICN-SIGN")))
            {
                localVarHeaderParams["ICN-SIGN"] = this.Configuration.GetApiKeyWithPrefix("ICN-SIGN");
            }
            // authentication (ApiTimestamp) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ICN-TIMESTAMP")))
            {
                localVarHeaderParams["ICN-TIMESTAMP"] = this.Configuration.GetApiKeyWithPrefix("ICN-TIMESTAMP");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SubmitStructure", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Structure>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (Structure) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Structure)));
        }

    }
}
