/* 
 * Iconomi API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IconomiApi.Client.SwaggerDateConverter;

namespace IconomiApi.Model
{
    /// <summary>
    /// SubmitStructureElement
    /// </summary>
    [DataContract]
        public partial class SubmitStructureElement :  IEquatable<SubmitStructureElement>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitStructureElement" /> class.
        /// </summary>
        /// <param name="assetTicker">assetTicker.</param>
        /// <param name="rebalancedWeight">rebalancedWeight.</param>
        public SubmitStructureElement(string assetTicker = default(string), decimal? rebalancedWeight = default(decimal?))
        {
            this.AssetTicker = assetTicker;
            this.RebalancedWeight = rebalancedWeight;
        }
        
        /// <summary>
        /// Gets or Sets AssetTicker
        /// </summary>
        [DataMember(Name="assetTicker", EmitDefaultValue=true)]
        public string AssetTicker { get; set; }

        /// <summary>
        /// Gets or Sets RebalancedWeight
        /// </summary>
        [DataMember(Name="rebalancedWeight", EmitDefaultValue=true)]
        public decimal? RebalancedWeight { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubmitStructureElement {\n");
            sb.Append("  AssetTicker: ").Append(AssetTicker).Append("\n");
            sb.Append("  RebalancedWeight: ").Append(RebalancedWeight).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SubmitStructureElement);
        }

        /// <summary>
        /// Returns true if SubmitStructureElement instances are equal
        /// </summary>
        /// <param name="input">Instance of SubmitStructureElement to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubmitStructureElement input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AssetTicker == input.AssetTicker ||
                    (this.AssetTicker != null &&
                    this.AssetTicker.Equals(input.AssetTicker))
                ) && 
                (
                    this.RebalancedWeight == input.RebalancedWeight ||
                    (this.RebalancedWeight != null &&
                    this.RebalancedWeight.Equals(input.RebalancedWeight))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AssetTicker != null)
                    hashCode = hashCode * 59 + this.AssetTicker.GetHashCode();
                if (this.RebalancedWeight != null)
                    hashCode = hashCode * 59 + this.RebalancedWeight.GetHashCode();
                return hashCode;
            }
        }
    }
}
